### ISSUE TITLE
Search very very slow

### ISSUE THREAD

**Issue by jay-schulz-openfellas** [IndieGoodies/PastePal#49] opened 2024-04-05 07:32 UTC
**Describe the bug**
Since about 2 weeks the search takes much longer - and since about 3 days it is incredibly slow, sometimes the application even hangs during the search. 

I start a search e.g. for TM: and the application starts to search and does not respond in the Activity Manager. 
At some point I get the result - until then I only see the "hourglass"

**To Reproduce**
1. Open Sidebar
2. CMD + F 
3. TM: 
4. wait/lags

** Screenshots **

![Bildschirmfoto 2024-04-05 um 09 25 08](https://github.com/IndieGoodies/PastePal/assets/114235118/e57801fe-5b52-4fe8-be6b-35e3cf4635b6)

**Expected behavior**
Die Suche soll wieder so performant und schnell sein wie vorher. 

**Desktop (please complete the following information):**
 - OS: 14.4.1 (23E224)
 - PastPal:  AppStore 
 - Version 2.15.3

**Additional context**
I have already reduced my history from 6 months to 3 months.

**Comment by jay-schulz-openfellas** [comment] 2024-04-05 07:39
Additional information that I have forgotten - 
the diagnostic report.


[PastePal_2024-04-05-083643_Alpha-Moby.cpu_resource-diag.txt](https://github.com/IndieGoodies/PastePal/files/14881604/PastePal_2024-04-05-083643_Alpha-Moby.cpu_resource-diag.txt)

**Comment by spazbg** [comment] 2024-04-16 14:55
I can confirm that I have the same experience and it is very frustrating because I am freshly migrating from the snappy Maccy to PastePal, but this lag during searching - a main feature of the clipboard manager app - is **unacceptable**...

**Comment by onmyway133** [comment] 2024-04-21 06:36
@jay-schulz-openfellas @spazbg thanks for the feedback, I'm looking into this and will have the fix in upcoming release very soon

**Comment by onmyway133** [comment] 2024-04-22 06:00
@jay-schulz-openfellas @spazbg can you try latest version 2.15.4 to see if it has fixed the issue?

**Comment by spazbg** [comment] 2024-04-22 06:29
I am already on Version 2.15.4 (169).
Could you tell me if there are any recommended settings, for example, "Items per page" or "Display items"? I was using 100, now I reduced them to 50 and it feels better, or maybe it's from the update

**Comment by jay-schulz-openfellas** [comment] 2024-04-22 06:47
I completely restarted a week ago without a backup (deleting the entire history) - during this time it was sometimes unusable.

At the moment it's running smoothly again - just like before. 
I'll gather experience for a day or two and report back here.

Thanks for your support.

**Comment by onmyway133** [comment] 2024-04-22 08:59
@spazbg It was due to the way I rendered support for large content which wasn't optimal, now I improved that and it should work better

**Comment by jay-schulz-openfellas** [comment] 2024-04-25 07:24
@onmyway133 i can report for me. 
All works fine again - many thanks for you support. 

Just info - i'm allready - Premium user. 

![Bildschirmfoto 2024-04-25 um 09 22 37](https://github.com/IndieGoodies/PastePal/assets/114235118/0209ebee-583e-4d89-81b6-14db1bc9a9a9)

**Comment by onmyway133** [comment] 2024-04-26 06:05
@jay-schulz-openfellas thanks for letting me know, and thanks for supporting the app ❤️ . I will close this issue for now, feel free to ping me again if you have any questions

**Closed as completed by onmyway133** 2024-04-26 06:05 UTC
Labels: fix
